### ISSUE TITLE
Depends On Suite not finding my test suite

### ISSUE THREAD

**Issue by apelling15** [mentalisttraceur/robotframework-dependencylibrary#8]
I'm struggling when using the Depends On Suite keyword.

I've got an initial test suite that does a lot of preparatory setup work. After this has run, a secondary suite kicks off, which is dependant on the first one.

However, when using the "Depends On Suite" keyword, I get a warning that my initial test suite was not found:
![image](https://user-images.githubusercontent.com/128608444/226949585-20bcb086-634d-4cc9-b597-aa91aa4d1847.png)

I am checking the the dependency in the suite setup of 1 Salesforce.robot.

**Comment by mentalisttraceur** [comment]
Thanks for the report!

First thing, let's make sure you have `Library  DependencyLibrary` in the `*** Settings ***` section of `0 Initial Setup.robot`.

(Unfortunately, `DependencyLibrary` has to be included in every suite whose results we want to depend on, because of how Robot Framework's listener interface works. I'll try to update the README to make that clear in the near future.)

**Comment by mentalisttraceur** [comment]
Alternatively, as of the just-released v4.0.1, adding `--listener DependencyLibrary` to the `robot` command invocation should now work, eliminating the need to import the library in depended-on suites.

(I managed to work around Robot Framework's listener interface quirks by refactoring `DependencyLibrary` to be a from-module Robot library instead of a from-class Robot library.)

**Comment by mentalisttraceur** [comment]
I think the above should solve your problem, but let me know if it doesn't and I'll re-open this issue!

**Comment by apelling15** [comment]
Thank you for your very quick response! Ensuring that the library is impoted in my initial suite was the problem! Thank you - I was scratching my head over this one for some time before asking for assistance here!
